# Generated by Django 3.0.10 on 2020-10-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201026_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
